### ISSUE TITLE
Package body of memcached-plsql package;

### ISSUE THREAD

**Issue by MaksimIvanovPerm** [amartinmassoni/plsql-memcached#1]
Hello amartinmassoni;
First of all: thank you for sharing this piece of plsql-code;
Githab says that it was uploaded over 4 years ago, so, probably, you have other interests now;
But, just in case, I will clarify: would you like to add package-body of your memcached-plsql package?

**Comment by amartinmassoni** [comment]
Hello
I have added the package body, I wrote it in 2015 and forgot to push it to github.
I don't remember if I tested it, use it at your own risk!
